version: "3.9"

services:

  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "8000:8000"


  frontend:
    build: ./frontend
    restart: always
    depends_on: 
      - backend
    ports:
      - "3000:3000"