name: Docker Compose Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker Compose stack
      run: docker-compose build

    - name: Run the Docker Compose stack
      run: docker-compose up -d

    - name: Test the backend service
      run: |
        # Wait for the backend service to be ready
        sleep 30
        # Test the backend service
        curl http://localhost:8000/health

    - name: Test the frontend service
      run: |
        # Wait for the frontend service to be ready
        sleep 30
        # Test the frontend service
        curl http://localhost:3000

    - name: Stop the Docker Compose stack
      if: always()
      run: docker-compose down